name: CI (bleeding edge)
# goals: check stability against
# - dev version of numpy, matplotlib, scipy, h5py and astropy
# - building with future pip default options

on:
  push:
    branches:
    - main
  pull_request:
    paths:
    - .github/workflows/bleeding-edge.yaml
  schedule:
    # run this every Wednesday at 3 am UTC
  - cron: 0 3 * * 3
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Dev upstream
    timeout-minutes: 60

    steps:
    - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      with:
        fetch-depth: 0

    - name: Setup uv
      uses: astral-sh/setup-uv@85856786d1ce8acfbcc2f13a5f3fbd6b938f9f41 # v7.1.2
      with:
        python-version: '3.14'
        enable-cache: false

    - name: configure uv
      run: |
        echo "UV_PRERELEASE=allow" >> $GITHUB_ENV
        echo "UV_INDEX=https://pypi.anaconda.org/scientific-python-nightly-wheels/simple https://pypi.anaconda.org/astropy/simple/ https://pypi.anaconda.org/liberfa/simple" >> $GITHUB_ENV
        echo "UV_INDEX_STRATEGY=unsafe-best-match" >> $GITHUB_ENV

    - name: upgrade lockfile
      run: uv lock --upgrade

    - name: Build amical
      run: uv sync --no-editable --group test

    - name: Run tests
      run: uv run --no-sync pytest --color=yes
